#!/bin/bash

set -e

# Stellar Testnet Deployment Script
# Deploys contracts in order: registry → escrow → settlement
# Wires authorized contract addresses between contracts
# Outputs deployed contract IDs to .env.testnet

NETWORK="testnet"
RPC_URL="https://soroban-testnet.stellar.org:443"
SOURCE_WALLET=".deploy/wallet.json"
ENV_FILE=".env.testnet"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Stellar Testnet Deployment ===${NC}"

# Create .deploy directory if it doesn't exist
mkdir -p .deploy

# Generate or load wallet
if [ ! -f "$SOURCE_WALLET" ]; then
    echo -e "${YELLOW}Generating new wallet...${NC}"
    stellar keys generate --network "$NETWORK" --rpc-url "$RPC_URL" --output "$SOURCE_WALLET"
else
    echo -e "${YELLOW}Using existing wallet${NC}"
fi

# Get public key
PUBLIC_KEY=$(stellar keys address --network "$NETWORK" --rpc-url "$RPC_URL" --source "$SOURCE_WALLET")
echo -e "${GREEN}Deployer Address: $PUBLIC_KEY${NC}"

# Fund account via Friendbot if needed
echo -e "${YELLOW}Funding account via Friendbot...${NC}"
curl -X POST "https://friendbot.stellar.org/?addr=$PUBLIC_KEY" || echo "Account may already be funded"

# Build contracts
echo -e "${YELLOW}Building contracts...${NC}"
cargo build --target wasm32-unknown-unknown --release

# Optimize contracts
echo -e "${YELLOW}Optimizing contracts...${NC}"
soroban optimize contracts/registry/target/wasm32-unknown-unknown/release/registry.wasm -o .deploy/registry.wasm
soroban optimize contracts/escrow/target/wasm32-unknown-unknown/release/escrow.wasm -o .deploy/escrow.wasm
soroban optimize contracts/settlement/target/wasm32-unknown-unknown/release/settlement.wasm -o .deploy/settlement.wasm

# Deploy Registry Contract
echo -e "${YELLOW}Deploying Registry contract...${NC}"
REGISTRY_ID=$(soroban contract deploy \
    --wasm .deploy/registry.wasm \
    --source "$SOURCE_WALLET" \
    --network "$NETWORK" \
    --rpc-url "$RPC_URL")

echo -e "${GREEN}Registry deployed: $REGISTRY_ID${NC}"

# Deploy Escrow Contract
echo -e "${YELLOW}Deploying Escrow contract...${NC}"
ESCROW_ID=$(soroban contract deploy \
    --wasm .deploy/escrow.wasm \
    --source "$SOURCE_WALLET" \
    --network "$NETWORK" \
    --rpc-url "$RPC_URL")

echo -e "${GREEN}Escrow deployed: $ESCROW_ID${NC}"

# Deploy Settlement Contract
echo -e "${YELLOW}Deploying Settlement contract...${NC}"
SETTLEMENT_ID=$(soroban contract deploy \
    --wasm .deploy/settlement.wasm \
    --source "$SOURCE_WALLET" \
    --network "$NETWORK" \
    --rpc-url "$RPC_URL")

echo -e "${GREEN}Settlement deployed: $SETTLEMENT_ID${NC}"

# Initialize Registry with admin and escrow address
echo -e "${YELLOW}Initializing Registry contract...${NC}"
soroban contract invoke \
    --id "$REGISTRY_ID" \
    --source "$SOURCE_WALLET" \
    --network "$NETWORK" \
    --rpc-url "$RPC_URL" \
    -- initialize \
    --admin "$PUBLIC_KEY" \
    --escrow_contract "$ESCROW_ID"

# Initialize Escrow with admin, registry, and settlement addresses
echo -e "${YELLOW}Initializing Escrow contract...${NC}"
soroban contract invoke \
    --id "$ESCROW_ID" \
    --source "$SOURCE_WALLET" \
    --network "$NETWORK" \
    --rpc-url "$RPC_URL" \
    -- initialize \
    --admin "$PUBLIC_KEY" \
    --registry_contract "$REGISTRY_ID" \
    --settlement_contract "$SETTLEMENT_ID"

# Initialize Settlement with admin, registry, and escrow addresses
echo -e "${YELLOW}Initializing Settlement contract...${NC}"
soroban contract invoke \
    --id "$SETTLEMENT_ID" \
    --source "$SOURCE_WALLET" \
    --network "$NETWORK" \
    --rpc-url "$RPC_URL" \
    -- initialize \
    --admin "$PUBLIC_KEY" \
    --registry_contract "$REGISTRY_ID" \
    --escrow_contract "$ESCROW_ID"

# Write contract IDs to .env.testnet
echo -e "${YELLOW}Writing contract IDs to .env.testnet${NC}"
cat > "$ENV_FILE" << EOF
# Stellar Testnet Deployment
# Generated by scripts/deploy.sh

NETWORK=testnet
RPC_URL=https://soroban-testnet.stellar.org:443
DEPLOYER_ADDRESS=$PUBLIC_KEY

REGISTRY_CONTRACT_ID=$REGISTRY_ID
ESCROW_CONTRACT_ID=$ESCROW_ID
SETTLEMENT_CONTRACT_ID=$SETTLEMENT_ID
EOF

echo -e "${GREEN}=== Deployment Complete ===${NC}"
echo -e "${GREEN}Registry: $REGISTRY_ID${NC}"
echo -e "${GREEN}Escrow: $ESCROW_ID${NC}"
echo -e "${GREEN}Settlement: $SETTLEMENT_ID${NC}"
echo -e "${YELLOW}Contract IDs saved to $ENV_FILE${NC}"
