#!/bin/bash
set -e

# Stellar Testnet Deployment Script
# Deploys contracts in order: registry → escrow → settlement
# Wires authorized contract addresses between contracts
# Outputs contract IDs to .env.testnet

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
NETWORK="testnet"
RPC_URL="https://soroban-testnet.stellar.org:443"
ENV_FILE=".env.testnet"

# Load environment variables
if [ -f "$ENV_FILE" ]; then
    source "$ENV_FILE"
fi

# Check if secret key is set
if [ -z "$DEPLOYER_SECRET_KEY" ]; then
    echo -e "${RED}Error: DEPLOYER_SECRET_KEY not set in $ENV_FILE${NC}"
    echo "Please set DEPLOYER_SECRET_KEY in $ENV_FILE"
    exit 1
fi

echo -e "${GREEN}=== Stellar Testnet Deployment ===${NC}"
echo "Network: $NETWORK"
echo "RPC URL: $RPC_URL"
echo ""

# Function to deploy contract
deploy_contract() {
    local contract_name=$1
    local contract_path=$2
    local wasm_file="${contract_path}/target/wasm32-unknown-unknown/release/${contract_name}.wasm"
    
    echo -e "${YELLOW}Deploying $contract_name...${NC}"
    
    # Check if wasm file exists
    if [ ! -f "$wasm_file" ]; then
        echo -e "${RED}Error: WASM file not found at $wasm_file${NC}"
        echo "Please build the contract first: cargo build --release --target wasm32-unknown-unknown"
        exit 1
    fi
    
    # Deploy contract
    local contract_id=$(soroban contract deploy \
        --wasm "$wasm_file" \
        --source "$DEPLOYER_SECRET_KEY" \
        --rpc-url "$RPC_URL" \
        --network-passphrase "Test SDF Network ; September 2015" \
        | grep -o '[a-zA-Z0-9]\{56\}')
    
    if [ -z "$contract_id" ]; then
        echo -e "${RED}Error: Failed to deploy $contract_name${NC}"
        exit 1
    fi
    
    echo -e "${GREEN}✓ $contract_name deployed: $contract_id${NC}"
    echo "$contract_id"
}

# Function to invoke contract
invoke_contract() {
    local contract_id=$1
    local function_name=$2
    local args=$3
    
    soroban contract invoke \
        --id "$contract_id" \
        --fn "$function_name" \
        --source "$DEPLOYER_SECRET_KEY" \
        --rpc-url "$RPC_URL" \
        --network-passphrase "Test SDF Network ; September 2015" \
        $args
}

# Build contracts
echo -e "${YELLOW}Building contracts...${NC}"
cargo build --release --target wasm32-unknown-unknown
echo -e "${GREEN}✓ Contracts built${NC}"
echo ""

# Deploy Registry
REGISTRY_ID=$(deploy_contract "registry" "contracts/registry")

# Deploy Escrow
ESCROW_ID=$(deploy_contract "escrow" "contracts/escrow")

# Deploy Settlement
SETTLEMENT_ID=$(deploy_contract "settlement" "contracts/settlement")

echo ""
echo -e "${YELLOW}Initializing contracts...${NC}"

# Initialize Registry
echo "Initializing Registry..."
invoke_contract "$REGISTRY_ID" "init" "--admin $DEPLOYER_SECRET_KEY"
echo -e "${GREEN}✓ Registry initialized${NC}"

# Initialize Escrow with registry address
echo "Initializing Escrow..."
invoke_contract "$ESCROW_ID" "init" "--registry $REGISTRY_ID --admin $DEPLOYER_SECRET_KEY"
echo -e "${GREEN}✓ Escrow initialized${NC}"

# Initialize Settlement with escrow and registry addresses
echo "Initializing Settlement..."
invoke_contract "$SETTLEMENT_ID" "init" "--escrow $ESCROW_ID --registry $REGISTRY_ID --admin $DEPLOYER_SECRET_KEY"
echo -e "${GREEN}✓ Settlement initialized${NC}"

echo ""
echo -e "${GREEN}=== Deployment Complete ===${NC}"

# Get deployer public key
DEPLOYER_PUBLIC_KEY=$(soroban keys derive --secret-key "$DEPLOYER_SECRET_KEY" | grep -o 'G[a-zA-Z0-9]\{55\}')

# Write to .env.testnet
cat > "$ENV_FILE" << EOF
# Stellar Testnet Configuration
# Generated by deploy.sh - do not edit manually

# Network
STELLAR_NETWORK=testnet
STELLAR_RPC_URL=https://soroban-testnet.stellar.org:443

# Deployer Account
DEPLOYER_SECRET_KEY=$DEPLOYER_SECRET_KEY
DEPLOYER_PUBLIC_KEY=$DEPLOYER_PUBLIC_KEY

# Contract IDs
REGISTRY_CONTRACT_ID=$REGISTRY_ID
ESCROW_CONTRACT_ID=$ESCROW_ID
SETTLEMENT_CONTRACT_ID=$SETTLEMENT_ID

# Wave Program (for testing)
WAVE_PROGRAM_ID=
WAVE_ID=
EOF

echo -e "${GREEN}Contract IDs written to $ENV_FILE${NC}"
echo ""
echo "Contract IDs:"
echo "  Registry:  $REGISTRY_ID"
echo "  Escrow:    $ESCROW_ID"
echo "  Settlement: $SETTLEMENT_ID"
echo ""
echo -e "${GREEN}Deployment successful!${NC}"
