# Stellar Testnet Deployment Script (PowerShell)
# Deploys contracts in order: registry → escrow → settlement
# Wires authorized contract addresses between contracts
# Outputs deployed contract IDs to .env.testnet

$ErrorActionPreference = "Stop"

$NETWORK = "testnet"
$RPC_URL = "https://soroban-testnet.stellar.org:443"
$SOURCE_WALLET = ".deploy\wallet.json"
$ENV_FILE = ".env.testnet"

Write-Host "=== Stellar Testnet Deployment ===" -ForegroundColor Green

# Create .deploy directory if it doesn't exist
if (-not (Test-Path ".deploy")) {
    New-Item -ItemType Directory -Path ".deploy" | Out-Null
}

# Generate or load wallet
if (-not (Test-Path $SOURCE_WALLET)) {
    Write-Host "Generating new wallet..." -ForegroundColor Yellow
    stellar keys generate --network $NETWORK --rpc-url $RPC_URL --output $SOURCE_WALLET
} else {
    Write-Host "Using existing wallet" -ForegroundColor Yellow
}

# Get public key
$PUBLIC_KEY = stellar keys address --network $NETWORK --rpc-url $RPC_URL --source $SOURCE_WALLET
Write-Host "Deployer Address: $PUBLIC_KEY" -ForegroundColor Green

# Fund account via Friendbot if needed
Write-Host "Funding account via Friendbot..." -ForegroundColor Yellow
try {
    Invoke-WebRequest -Uri "https://friendbot.stellar.org/?addr=$PUBLIC_KEY" -Method Post | Out-Null
} catch {
    Write-Host "Account may already be funded" -ForegroundColor Yellow
}

# Build contracts
Write-Host "Building contracts..." -ForegroundColor Yellow
cargo build --target wasm32-unknown-unknown --release

# Optimize contracts
Write-Host "Optimizing contracts..." -ForegroundColor Yellow
soroban optimize contracts\registry\target\wasm32-unknown-unknown\release\registry.wasm -o .deploy\registry.wasm
soroban optimize contracts\escrow\target\wasm32-unknown-unknown\release\escrow.wasm -o .deploy\escrow.wasm
soroban optimize contracts\settlement\target\wasm32-unknown-unknown\release\settlement.wasm -o .deploy\settlement.wasm

# Deploy Registry Contract
Write-Host "Deploying Registry contract..." -ForegroundColor Yellow
$REGISTRY_ID = soroban contract deploy --wasm .deploy\registry.wasm --source $SOURCE_WALLET --network $NETWORK --rpc-url $RPC_URL
Write-Host "Registry deployed: $REGISTRY_ID" -ForegroundColor Green

# Deploy Escrow Contract
Write-Host "Deploying Escrow contract..." -ForegroundColor Yellow
$ESCROW_ID = soroban contract deploy --wasm .deploy\escrow.wasm --source $SOURCE_WALLET --network $NETWORK --rpc-url $RPC_URL
Write-Host "Escrow deployed: $ESCROW_ID" -ForegroundColor Green

# Deploy Settlement Contract
Write-Host "Deploying Settlement contract..." -ForegroundColor Yellow
$SETTLEMENT_ID = soroban contract deploy --wasm .deploy\settlement.wasm --source $SOURCE_WALLET --network $NETWORK --rpc-url $RPC_URL
Write-Host "Settlement deployed: $SETTLEMENT_ID" -ForegroundColor Green

# Initialize Registry with admin and escrow address
Write-Host "Initializing Registry contract..." -ForegroundColor Yellow
soroban contract invoke --id $REGISTRY_ID --source $SOURCE_WALLET --network $NETWORK --rpc-url $RPC_URL -- initialize --admin $PUBLIC_KEY --escrow_contract $ESCROW_ID

# Initialize Escrow with admin, registry, and settlement addresses
Write-Host "Initializing Escrow contract..." -ForegroundColor Yellow
soroban contract invoke --id $ESCROW_ID --source $SOURCE_WALLET --network $NETWORK --rpc-url $RPC_URL -- initialize --admin $PUBLIC_KEY --registry_contract $REGISTRY_ID --settlement_contract $SETTLEMENT_ID

# Initialize Settlement with admin, registry, and escrow addresses
Write-Host "Initializing Settlement contract..." -ForegroundColor Yellow
soroban contract invoke --id $SETTLEMENT_ID --source $SOURCE_WALLET --network $NETWORK --rpc-url $RPC_URL -- initialize --admin $PUBLIC_KEY --registry_contract $REGISTRY_ID --escrow_contract $ESCROW_ID

# Write contract IDs to .env.testnet
Write-Host "Writing contract IDs to $ENV_FILE" -ForegroundColor Yellow
@"
# Stellar Testnet Deployment
# Generated by scripts/deploy.ps1

NETWORK=testnet
RPC_URL=https://soroban-testnet.stellar.org:443
DEPLOYER_ADDRESS=$PUBLIC_KEY

REGISTRY_CONTRACT_ID=$REGISTRY_ID
ESCROW_CONTRACT_ID=$ESCROW_ID
SETTLEMENT_CONTRACT_ID=$SETTLEMENT_ID
"@ | Out-File -FilePath $ENV_FILE -Encoding UTF8

Write-Host "=== Deployment Complete ===" -ForegroundColor Green
Write-Host "Registry: $REGISTRY_ID" -ForegroundColor Green
Write-Host "Escrow: $ESCROW_ID" -ForegroundColor Green
Write-Host "Settlement: $SETTLEMENT_ID" -ForegroundColor Green
Write-Host "Contract IDs saved to $ENV_FILE" -ForegroundColor Yellow
